
[webservers]
web-1 ansible_host=111.88.250.97 fqdn=fhmndtm4bbq0sietub9t.auto.internal
web-2 ansible_host=111.88.243.200 fqdn=fhmsaalqcqsugse6nmmc.auto.internal

[databases]
main ansible_host=111.88.248.171 fqdn=fhmu5jiq6ljh130e7lh0.auto.internal
replica ansible_host=111.88.245.233 fqdn=fhm630m1n3gk03gd0310.auto.internal

[storage]
storage ansible_host=111.88.241.138 fqdn=fhmo6hble9l9q5iicoqm.auto.internal
